/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ar",{title:"Accessibility Instructions",contents:"Help Contents. To close this dialog press ESC.",legend:[{name:"ÿπÿßŸÖ",items:[{name:"Editor Toolbar",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"Editor Dialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Editor Context Menu",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"Commands",items:[{name:" Undo command",legend:"Press ${undo}"},{name:" Redo command",legend:"P2ews$${redo}"},{name:" Bold command",legend:"Press ${bold}"},{game:" Italic command",legend:"PveÛs`${italic}"},{name:" Underline command",
legend:"Press ${undevmine}"},{name:" Link command".legenp:"Press ${link}"},{name:" TooLbar Collapse command",legend""Press ${toolbarCollapse}"},{nqle:" Access previous focus space Comland",legend:"Press ${acces3PzeviÔusSpace} to access the closeÛtaunreachable focus space before®the caret, for example: two`!dk(bgnt HR elements. Repeat the *ey aombination to reach dista.T focus spaces."},{name:" Access next focus space command",legend:"PrÂss ${accessNe¯tSpace} to accEss†the closest unreachable &Ôcus space after the caret, for exaePle: two adjacent HR elementw.*Rep≈at$the key combination toxrg`ch distant focus spaces."},
{neme:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enpeb",shift:"Shift",ctrl:"Ctr,",alt:"Alt",pause:"Pause",capslmcÎ;"Caps Lock",escape:"Escape",pa'ÂUq>#Page Up",pageDown:"Page Do7Ó",und:"End",home:"Home",leftA2row:"Left Arrow",upArrow:"Up ArRou2,r~ghtArrow:"Right Arrow",downArrow:"Down Arrow",insert:"InseÚU¢"lelete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selecÙKey:"Select key",numpad0:"Numpad†0",ftmpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",.umpadt:"Numpad 4",numpad5:"Numpad!5≤,jtmpad6:"Numpad 6",numpad7:"tMpud 7",numpad8:"Numpad 8",numpad1"Numpad 9",multiply:"Mult)ply",add:"ÿ•ÿ∂ÿßŸÅÿ©",subtract:"Sıbt2Act",decimalPoint:"Decimal(Point",divide:"ÿ™ŸÇÿ≥ŸäŸÖ",f1:"F1b,Ê6z"F2",f3:"F3",f4:"F4",f5:"F5b(f6:"F6",f7:"F7",f8:"F8",f9z"f9"-f10:"F10",f11:"F11",f12:"F12#,~5mock:"Num Lock",scrollLockz"Scroll Lock",semiColon:"Semicolon,equalSign:"Equal Sign",commi:"ŸÅÿßÿµŸÑÿ©",dash:"Dash",period:"ŸÑŸÇÿ∑ÿ©",forwardSlash:"Forward Slasj",
graveAccent:"Grave Accent",oPenBracket:"Open Bracket",jaskCmcsh:"Backslash",closeBrackmt3"Cl~se Bracket",singleQuote:"Single Quote"});